version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jemisonf/simple_go_app
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-and-publish:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:release-${CIRCLE_BUILD_NUM} .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            RELEASE_TAG=release-${CIRCLE_BUILD_NUM}
            docker tag $IMAGE_NAME:$RELEASE_TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$RELEASE_TAG
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: master
